// Pure logic behind accepting a useful title emitted by an agent's terminal.
//
// Kept deliberately separate from `sessions.ts`'s `tab/autoTitled` reducer
// action: this module validates the engine-provided title, while the
// reducer decides whether it may replace the current label.

/** Truncated title length ("~40-50 chars" per the brief) — long enough to
 * stay recognizable, short enough that a pane header never wraps/crowds
 * out the branch pill and buttons next to it. */
export const AUTO_TITLE_MAX_LENGTH = 48;

/** Truncates `s` to at most `maxLen` characters, trimming any trailing
 * whitespace the cut would otherwise leave right before the ellipsis. */
export function truncateTitle(s: string, maxLen: number): string {
  if (s.length <= maxLen) return s;
  return `${s.slice(0, maxLen - 1).trimEnd()}…`;
}

/**
 * Turns a terminal title into readable text: strips ANSI CSI escape
 * sequences, replays backspace (`\x7f`/`\b`), drops remaining C0 control
 * characters (tab excepted), and trims the result.
 */
export function sanitizeForTitle(raw: string): string {
  let out = "";
  let i = 0;
  while (i < raw.length) {
    const ch = raw[i];
    if (ch === "\x1b") {
      // CSI (ESC '[' ... final-byte) or a bare two-byte escape — skip it
      // entirely rather than let it leak literal escape junk into a title.
      if (raw[i + 1] === "[") {
        let j = i + 2;
        while (j < raw.length && !/[a-zA-Z~]/.test(raw[j])) j++;
        i = Math.min(j + 1, raw.length);
      } else {
        i += 2;
      }
      continue;
    }
    if (ch === "\x7f" || ch === "\b") {
      out = out.slice(0, -1);
      i++;
      continue;
    }
    if (ch.charCodeAt(0) < 0x20 && ch !== "\t") {
      i++;
      continue;
    }
    out += ch;
    i++;
  }
  return out.trim();
}

/** `null` for a title that sanitizes down to nothing. */
export function titleFromLine(rawLine: string): string | null {
  const clean = sanitizeForTitle(rawLine);
  if (clean.length === 0) return null;
  return truncateTitle(clean, AUTO_TITLE_MAX_LENGTH);
}

/**
 * Accept only the useful OSC titles generated by Claude Code or Copilot.
 * Other engines do not expose a reliable summary title, and startup titles
 * such as Claude's version are not task names.
 */
export function engineTitleFromTerminalTitle(engine: string, rawTitle: string): string | null {
  if (engine !== "claude" && engine !== "copilot") return null;
  const title = titleFromLine(rawTitle);
  if (!title || /^(claude(?: code)?|github copilot|copilot|\d+(?:\.\d+){1,3})$/i.test(title)) return null;
  return title;
}
